### ISSUE TITLE
Running the Demo locally throws error.

### ISSUE THREAD

**Issue by astericky** [theogravity/react-styleguide-generator-alt#62]
`bundle.js:562 Warning: _class(...): No 'render' method found on the returned component instance: you may have forgotten to define 'render', returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

bundle.js:83107 Uncaught TypeError: inst.render is not a function`

I am not sure what I am doing wrong here to get this error. I cloned the repo then I ran `npm install` and then I ran `npm start` and I got an error just trying to run the demo at all. It's also unclear how to insert it as a folder in the general codebase. 

Any help would be greatly appreciated. Thanks!

**Comment by bendman** [comment]
After doing a bisect, this was triggered by commit f3329ee, but seems to be because of a requirement in React 0.14 that was dropped in 0.15, [as per the docs](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions):

> NOTE:
> In React v0.14, stateless functional components were not permitted to return null or false (a workaround is to return a <noscript /> instead). This was fixed in React v15, and stateless functional components are now permitted to return null.

**Comment by theogravity** [comment]
I'm guessing the fix is to do `Content || <noscript />` since rsg is using react 14 for dev?

**Comment by bendman** [comment]
Unfortunately that didn't work, since `Content` exists, it just doesn't have a render method (or a return value).  After looking into it, it's a bug that wasn't hit before because there was a check specifically for a render method on a class.

The problem is that `example/components/Features/Additional examples in tabs.js` has no render method, but I'm putting together a fix since it's blocking my work on #63.
