### ISSUE TITLE
Font: Declaration In Styling Causing Issues

### ISSUE THREAD

**Issue by lmosele** [theogravity/react-styleguide-generator-alt#63]
It's a small thing that's causing a bit of a headache, but as of right now the `font` declaration:

`font: 300 14px "Helvetica Neue", Helvetica, Arial, sans-serif;`

Is affecting all of my component's typography since it is included in `.sg` and many of its children. Would it be better to let the user decide what font-family they want to use rather than making them overwrite the base RSG styles?

**Comment by theogravity** [comment]
I'm for a config option for it

**Comment by bendman** [comment]
To fix the font so it doesn't break your typography, it seems like the answer would be to just fix the `rsg` CSS to not declare inheritable styles on every individual component.  The `.sg` selector properties could just be applied to `html` or `body`, so as to not break inheritance and cascading styles.

As for customizability of the base styles, we're hitting the same issue, but not just for the font.  It would be a more general solution to have a config option for the stylesheet itself, so you could:

#### Load additional stylesheets that act as an override
This is already possible using the "files" config option, and just setting an override style with more specificity than the built in styles, it's just harder because you need to override with more specificity.

#### Load a *different* stylesheet for the base
This would take some (minor) updates to the way `rsg` builds its styles.  Right now it seems like `rsg` injects styles into the page in a `<style>` tag, which makes it harder to override. This could change to use the `ExtractTextPlugin` and output a CSS file which is loaded on the page before anything defined in the `files` config, making it easier to override styles (as they wouldn't need to be *more* specific).  Then there could also be a `baseStylesheet` config that lets you turn off the base styles so you can just include your custom stylesheet.

**Comment by theogravity** [comment]
Prob the second option since you don't have to worry about specificity as much compared to the first. I'm completely open to any PRs that make working with the CSS more managable

**Comment by theogravity** [comment]
thanks @bendman !
